# Generated by Django 5.1.1 on 2024-09-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_date_created_remove_blog_starred_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
