# Generated by Django 5.1.1 on 2024-09-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_profile_photo_alter_user_role'),
        ('authentication', '0004_auto_20240926_1436'),
    ]

    operations = [
    ]
